//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.AdmiM004V00101 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:admi.004.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:admi.004.001.01", IsNullable=false)]
    public partial class Document {
        
        private admi00400101 admi00400101Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("admi.004.001.01")]
        public admi00400101 admi00400101 {
            get {
                return this.admi00400101Field;
            }
            set {
                this.admi00400101Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="admi.004.001.01", Namespace="urn:iso:std:iso:20022:tech:xsd:admi.004.001.01")]
    public partial class admi00400101 {
        
        private Event1 evtInfField;
        
        /// <remarks/>
        public Event1 EvtInf {
            get {
                return this.evtInfField;
            }
            set {
                this.evtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:admi.004.001.01")]
    public partial class Event1 {
        
        private string evtCdField;
        
        private string[] evtParamField;
        
        private string evtDescField;
        
        private System.DateTime evtTmField;
        
        private bool evtTmFieldSpecified;
        
        /// <remarks/>
        public string EvtCd {
            get {
                return this.evtCdField;
            }
            set {
                this.evtCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EvtParam")]
        public string[] EvtParam {
            get {
                return this.evtParamField;
            }
            set {
                this.evtParamField = value;
            }
        }
        
        /// <remarks/>
        public string EvtDesc {
            get {
                return this.evtDescField;
            }
            set {
                this.evtDescField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EvtTm {
            get {
                return this.evtTmField;
            }
            set {
                this.evtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EvtTmSpecified {
            get {
                return this.evtTmFieldSpecified;
            }
            set {
                this.evtTmFieldSpecified = value;
            }
        }
    }
}
