//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.AcmtM021V00101 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IsNullable=false)]
    public partial class Document {
        
        private AccountClosingAdditionalInformationRequestV01 acctClsgAddtlInfReqField;
        
        /// <remarks/>
        public AccountClosingAdditionalInformationRequestV01 AcctClsgAddtlInfReq {
            get {
                return this.acctClsgAddtlInfReqField;
            }
            set {
                this.acctClsgAddtlInfReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class AccountClosingAdditionalInformationRequestV01 {
        
        private References3 refsField;
        
        private OrganisationIdentification6[] orgIdField;
        
        private AccountForAction1 acctIdField;
        
        private BranchAndFinancialInstitutionIdentification4 acctSvcrIdField;
        
        private AccountForAction1 balTrfAcctField;
        
        private BranchAndFinancialInstitutionIdentification4 trfAcctSvcrIdField;
        
        private PartyAndSignature1[] dgtlSgntrField;
        
        /// <remarks/>
        public References3 Refs {
            get {
                return this.refsField;
            }
            set {
                this.refsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId")]
        public OrganisationIdentification6[] OrgId {
            get {
                return this.orgIdField;
            }
            set {
                this.orgIdField = value;
            }
        }
        
        /// <remarks/>
        public AccountForAction1 AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification4 AcctSvcrId {
            get {
                return this.acctSvcrIdField;
            }
            set {
                this.acctSvcrIdField = value;
            }
        }
        
        /// <remarks/>
        public AccountForAction1 BalTrfAcct {
            get {
                return this.balTrfAcctField;
            }
            set {
                this.balTrfAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification4 TrfAcctSvcrId {
            get {
                return this.trfAcctSvcrIdField;
            }
            set {
                this.trfAcctSvcrIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DgtlSgntr")]
        public PartyAndSignature1[] DgtlSgntr {
            get {
                return this.dgtlSgntrField;
            }
            set {
                this.dgtlSgntrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class References3 {
        
        private MessageIdentification1 msgIdField;
        
        private MessageIdentification1 reqToBeCmpltdIdField;
        
        private MessageIdentification1 prcIdField;
        
        private string[] reqRsnField;
        
        private string[] attchdDocNmField;
        
        /// <remarks/>
        public MessageIdentification1 MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public MessageIdentification1 ReqToBeCmpltdId {
            get {
                return this.reqToBeCmpltdIdField;
            }
            set {
                this.reqToBeCmpltdIdField = value;
            }
        }
        
        /// <remarks/>
        public MessageIdentification1 PrcId {
            get {
                return this.prcIdField;
            }
            set {
                this.prcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReqRsn")]
        public string[] ReqRsn {
            get {
                return this.reqRsnField;
            }
            set {
                this.reqRsnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttchdDocNm")]
        public string[] AttchdDocNm {
            get {
                return this.attchdDocNmField;
            }
            set {
                this.attchdDocNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class MessageIdentification1 {
        
        private string idField;
        
        private System.DateTime creDtTmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class ContactDetails2 {
        
        private NamePrefix1Code nmPrfxField;
        
        private bool nmPrfxFieldSpecified;
        
        private string nmField;
        
        private string phneNbField;
        
        private string mobNbField;
        
        private string faxNbField;
        
        private string emailAdrField;
        
        private string othrField;
        
        /// <remarks/>
        public NamePrefix1Code NmPrfx {
            get {
                return this.nmPrfxField;
            }
            set {
                this.nmPrfxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NmPrfxSpecified {
            get {
                return this.nmPrfxFieldSpecified;
            }
            set {
                this.nmPrfxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public string PhneNb {
            get {
                return this.phneNbField;
            }
            set {
                this.phneNbField = value;
            }
        }
        
        /// <remarks/>
        public string MobNb {
            get {
                return this.mobNbField;
            }
            set {
                this.mobNbField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNb {
            get {
                return this.faxNbField;
            }
            set {
                this.faxNbField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public string Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public enum NamePrefix1Code {
        
        /// <remarks/>
        DOCT,
        
        /// <remarks/>
        MIST,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MADM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class PersonIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class GenericPersonIdentification1 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class DateAndPlaceOfBirth {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class PersonIdentification5 {
        
        private DateAndPlaceOfBirth dtAndPlcOfBirthField;
        
        private GenericPersonIdentification1[] othrField;
        
        /// <remarks/>
        public DateAndPlaceOfBirth DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericPersonIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class Party8Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification6))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification5))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class OrganisationIdentification6 {
        
        private string bICField;
        
        private GenericOrganisationIdentification1[] othrField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericOrganisationIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class GenericOrganisationIdentification1 {
        
        private string idField;
        
        private OrganisationIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public OrganisationIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class OrganisationIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class PartyIdentification41 {
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        private Party8Choice idField;
        
        private string ctryOfResField;
        
        private ContactDetails2 ctctDtlsField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public Party8Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
        
        /// <remarks/>
        public ContactDetails2 CtctDtls {
            get {
                return this.ctctDtlsField;
            }
            set {
                this.ctctDtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class PostalAddress6 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string deptField;
        
        private string subDeptField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        private string[] adrLineField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
        
        /// <remarks/>
        public string SubDept {
            get {
                return this.subDeptField;
            }
            set {
                this.subDeptField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class PartyAndSignature1 {
        
        private PartyIdentification41 ptyField;
        
        private System.Xml.XmlElement sgntrField;
        
        /// <remarks/>
        public PartyIdentification41 Pty {
            get {
                return this.ptyField;
            }
            set {
                this.ptyField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Sgntr {
            get {
                return this.sgntrField;
            }
            set {
                this.sgntrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class BranchData2 {
        
        private string idField;
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class FinancialIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class GenericFinancialIdentification1 {
        
        private string idField;
        
        private FinancialIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public FinancialIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class ClearingSystemIdentification2Choice {
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class ClearingSystemMemberIdentification2 {
        
        private ClearingSystemIdentification2Choice clrSysIdField;
        
        private string mmbIdField;
        
        /// <remarks/>
        public ClearingSystemIdentification2Choice ClrSysId {
            get {
                return this.clrSysIdField;
            }
            set {
                this.clrSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string MmbId {
            get {
                return this.mmbIdField;
            }
            set {
                this.mmbIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class FinancialInstitutionIdentification7 {
        
        private string bICField;
        
        private ClearingSystemMemberIdentification2 clrSysMmbIdField;
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        private GenericFinancialIdentification1 othrField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public ClearingSystemMemberIdentification2 ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public GenericFinancialIdentification1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class BranchAndFinancialInstitutionIdentification4 {
        
        private FinancialInstitutionIdentification7 finInstnIdField;
        
        private BranchData2 brnchIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentification7 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
        
        /// <remarks/>
        public BranchData2 BrnchId {
            get {
                return this.brnchIdField;
            }
            set {
                this.brnchIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class AccountSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class GenericAccountIdentification1 {
        
        private string idField;
        
        private AccountSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public AccountSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class AccountIdentification4Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.021.001.01")]
    public partial class AccountForAction1 {
        
        private AccountIdentification4Choice idField;
        
        private string ccyField;
        
        /// <remarks/>
        public AccountIdentification4Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
    }
}
