//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.AcmtM037V00101 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01", IsNullable=false)]
    public partial class Document {
        
        private AccountSwitchTechnicalRejectionV01 acctSwtchTechRjctnField;
        
        /// <remarks/>
        public AccountSwitchTechnicalRejectionV01 AcctSwtchTechRjctn {
            get {
                return this.acctSwtchTechRjctnField;
            }
            set {
                this.acctSwtchTechRjctnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public partial class AccountSwitchTechnicalRejectionV01 {
        
        private MessageIdentification1 msgIdField;
        
        private AccountSwitchDetails1 acctSwtchDtlsField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public MessageIdentification1 MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public AccountSwitchDetails1 AcctSwtchDtls {
            get {
                return this.acctSwtchDtlsField;
            }
            set {
                this.acctSwtchDtlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public partial class MessageIdentification1 {
        
        private string idField;
        
        private System.DateTime creDtTmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public partial class ResponseDetails1 {
        
        private string rspnCdField;
        
        private string addtlDtlsField;
        
        /// <remarks/>
        public string RspnCd {
            get {
                return this.rspnCdField;
            }
            set {
                this.rspnCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlDtls {
            get {
                return this.addtlDtlsField;
            }
            set {
                this.addtlDtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public partial class AccountSwitchDetails1 {
        
        private string unqRefNbField;
        
        private string rtgUnqRefNbField;
        
        private System.DateTime swtchRcvdDtTmField;
        
        private bool swtchRcvdDtTmFieldSpecified;
        
        private System.DateTime swtchDtField;
        
        private bool swtchDtFieldSpecified;
        
        private SwitchType1Code swtchTpField;
        
        private SwitchStatus1Code swtchStsField;
        
        private bool swtchStsFieldSpecified;
        
        private BalanceTransferWindow1Code balTrfWndwField;
        
        private bool balTrfWndwFieldSpecified;
        
        private ResponseDetails1[] rspnField;
        
        /// <remarks/>
        public string UnqRefNb {
            get {
                return this.unqRefNbField;
            }
            set {
                this.unqRefNbField = value;
            }
        }
        
        /// <remarks/>
        public string RtgUnqRefNb {
            get {
                return this.rtgUnqRefNbField;
            }
            set {
                this.rtgUnqRefNbField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SwtchRcvdDtTm {
            get {
                return this.swtchRcvdDtTmField;
            }
            set {
                this.swtchRcvdDtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwtchRcvdDtTmSpecified {
            get {
                return this.swtchRcvdDtTmFieldSpecified;
            }
            set {
                this.swtchRcvdDtTmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SwtchDt {
            get {
                return this.swtchDtField;
            }
            set {
                this.swtchDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwtchDtSpecified {
            get {
                return this.swtchDtFieldSpecified;
            }
            set {
                this.swtchDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SwitchType1Code SwtchTp {
            get {
                return this.swtchTpField;
            }
            set {
                this.swtchTpField = value;
            }
        }
        
        /// <remarks/>
        public SwitchStatus1Code SwtchSts {
            get {
                return this.swtchStsField;
            }
            set {
                this.swtchStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwtchStsSpecified {
            get {
                return this.swtchStsFieldSpecified;
            }
            set {
                this.swtchStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BalanceTransferWindow1Code BalTrfWndw {
            get {
                return this.balTrfWndwField;
            }
            set {
                this.balTrfWndwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalTrfWndwSpecified {
            get {
                return this.balTrfWndwFieldSpecified;
            }
            set {
                this.balTrfWndwFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rspn")]
        public ResponseDetails1[] Rspn {
            get {
                return this.rspnField;
            }
            set {
                this.rspnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public enum SwitchType1Code {
        
        /// <remarks/>
        FULL,
        
        /// <remarks/>
        PART,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public enum SwitchStatus1Code {
        
        /// <remarks/>
        ACPT,
        
        /// <remarks/>
        BTRQ,
        
        /// <remarks/>
        BTRS,
        
        /// <remarks/>
        COMP,
        
        /// <remarks/>
        REDT,
        
        /// <remarks/>
        REDE,
        
        /// <remarks/>
        REJT,
        
        /// <remarks/>
        REQU,
        
        /// <remarks/>
        TMTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:acmt.037.001.01")]
    public enum BalanceTransferWindow1Code {
        
        /// <remarks/>
        DAYH,
        
        /// <remarks/>
        EARL,
    }
}
