//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.PainM001V00301 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01", IsNullable=false)]
    public partial class Document {
        
        private pain00100301 pain00100301Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pain.001.003.01")]
        public pain00100301 pain00100301 {
            get {
                return this.pain00100301Field;
            }
            set {
                this.pain00100301Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="pain.001.003.01", Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class pain00100301 {
        
        private GroupInformation2 grpHdrField;
        
        private PaymentInformation7[] pmtInfField;
        
        /// <remarks/>
        public GroupInformation2 GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtInf")]
        public PaymentInformation7[] PmtInf {
            get {
                return this.pmtInfField;
            }
            set {
                this.pmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class GroupInformation2 {
        
        private string grpIdField;
        
        private System.DateTime creDtTmField;
        
        private string[] authstnField;
        
        private decimal ctrlSumField;
        
        private bool ctrlSumFieldSpecified;
        
        private bool btchBookgField;
        
        private bool btchBookgFieldSpecified;
        
        private string nbOfTxsField;
        
        private bool grpgField;
        
        private bool grpgFieldSpecified;
        
        private PartyIdentification1 initgPtyField;
        
        private BICIdentification1 fwdgAgtField;
        
        /// <remarks/>
        public string GrpId {
            get {
                return this.grpIdField;
            }
            set {
                this.grpIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Authstn")]
        public string[] Authstn {
            get {
                return this.authstnField;
            }
            set {
                this.authstnField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtrlSum {
            get {
                return this.ctrlSumField;
            }
            set {
                this.ctrlSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CtrlSumSpecified {
            get {
                return this.ctrlSumFieldSpecified;
            }
            set {
                this.ctrlSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool BtchBookg {
            get {
                return this.btchBookgField;
            }
            set {
                this.btchBookgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BtchBookgSpecified {
            get {
                return this.btchBookgFieldSpecified;
            }
            set {
                this.btchBookgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NbOfTxs {
            get {
                return this.nbOfTxsField;
            }
            set {
                this.nbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public bool Grpg {
            get {
                return this.grpgField;
            }
            set {
                this.grpgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrpgSpecified {
            get {
                return this.grpgFieldSpecified;
            }
            set {
                this.grpgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 InitgPty {
            get {
                return this.initgPtyField;
            }
            set {
                this.initgPtyField = value;
            }
        }
        
        /// <remarks/>
        public BICIdentification1 FwdgAgt {
            get {
                return this.fwdgAgtField;
            }
            set {
                this.fwdgAgtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PartyIdentification1 {
        
        private string nmField;
        
        private PostalAddress1 pstlAdrField;
        
        private Party1Choice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public Party1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PostalAddress1 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class ReferredDocumentAmount1Choice {
        
        private CurrencyAndAmount itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CdtNoteAmt", typeof(CurrencyAndAmount))]
        [System.Xml.Serialization.XmlElementAttribute("DscntApldAmt", typeof(CurrencyAndAmount))]
        [System.Xml.Serialization.XmlElementAttribute("DuePyblAmt", typeof(CurrencyAndAmount))]
        [System.Xml.Serialization.XmlElementAttribute("RmtdAmt", typeof(CurrencyAndAmount))]
        [System.Xml.Serialization.XmlElementAttribute("TaxAmt", typeof(CurrencyAndAmount))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public CurrencyAndAmount Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class CurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        CdtNoteAmt,
        
        /// <remarks/>
        DscntApldAmt,
        
        /// <remarks/>
        DuePyblAmt,
        
        /// <remarks/>
        RmtdAmt,
        
        /// <remarks/>
        TaxAmt,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class StructuredRemittanceInformation2 {
        
        private DocumentType1Code rfrdDocTpField;
        
        private bool rfrdDocTpFieldSpecified;
        
        private System.DateTime rfrdDocRltdDtField;
        
        private bool rfrdDocRltdDtFieldSpecified;
        
        private ReferredDocumentAmount1Choice[] rfrdDocAmtField;
        
        private string docRefNbField;
        
        private string cdtrRefField;
        
        private PartyIdentification1 invcrField;
        
        private PartyIdentification1 invceeField;
        
        /// <remarks/>
        public DocumentType1Code RfrdDocTp {
            get {
                return this.rfrdDocTpField;
            }
            set {
                this.rfrdDocTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfrdDocTpSpecified {
            get {
                return this.rfrdDocTpFieldSpecified;
            }
            set {
                this.rfrdDocTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RfrdDocRltdDt {
            get {
                return this.rfrdDocRltdDtField;
            }
            set {
                this.rfrdDocRltdDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfrdDocRltdDtSpecified {
            get {
                return this.rfrdDocRltdDtFieldSpecified;
            }
            set {
                this.rfrdDocRltdDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RfrdDocAmt")]
        public ReferredDocumentAmount1Choice[] RfrdDocAmt {
            get {
                return this.rfrdDocAmtField;
            }
            set {
                this.rfrdDocAmtField = value;
            }
        }
        
        /// <remarks/>
        public string DocRefNb {
            get {
                return this.docRefNbField;
            }
            set {
                this.docRefNbField = value;
            }
        }
        
        /// <remarks/>
        public string CdtrRef {
            get {
                return this.cdtrRefField;
            }
            set {
                this.cdtrRefField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Invcr {
            get {
                return this.invcrField;
            }
            set {
                this.invcrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Invcee {
            get {
                return this.invceeField;
            }
            set {
                this.invceeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum DocumentType1Code {
        
        /// <remarks/>
        MSIN,
        
        /// <remarks/>
        CNFA,
        
        /// <remarks/>
        DNFA,
        
        /// <remarks/>
        CINV,
        
        /// <remarks/>
        CREN,
        
        /// <remarks/>
        DEBN,
        
        /// <remarks/>
        HIRI,
        
        /// <remarks/>
        SBIN,
        
        /// <remarks/>
        RADM,
        
        /// <remarks/>
        RPIN,
        
        /// <remarks/>
        CMCN,
        
        /// <remarks/>
        FXDR,
        
        /// <remarks/>
        SOAC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class RemittanceInformation3Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strd", typeof(StructuredRemittanceInformation2))]
        [System.Xml.Serialization.XmlElementAttribute("Ustrd", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class AccountIdentification2 {
        
        private string iBANField;
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class EquivalentAmount {
        
        private CurrencyAndAmount amtField;
        
        private string ccyOfTrfField;
        
        /// <remarks/>
        public CurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public string CcyOfTrf {
            get {
                return this.ccyOfTrfField;
            }
            set {
                this.ccyOfTrfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class AmountType1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EqvtAmt", typeof(EquivalentAmount))]
        [System.Xml.Serialization.XmlElementAttribute("InstdAmt", typeof(CurrencyAndAmount))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PurposeChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PaymentPurpose1Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum PaymentPurpose1Code {
        
        /// <remarks/>
        SALA,
        
        /// <remarks/>
        TREA,
        
        /// <remarks/>
        ADVA,
        
        /// <remarks/>
        AGRT,
        
        /// <remarks/>
        ALMY,
        
        /// <remarks/>
        BECH,
        
        /// <remarks/>
        BENE,
        
        /// <remarks/>
        BONU,
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        CBFF,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        COLL,
        
        /// <remarks/>
        CMDT,
        
        /// <remarks/>
        COMC,
        
        /// <remarks/>
        COMM,
        
        /// <remarks/>
        COST,
        
        /// <remarks/>
        CPYR,
        
        /// <remarks/>
        DIVI,
        
        /// <remarks/>
        FREX,
        
        /// <remarks/>
        GDDS,
        
        /// <remarks/>
        GOVT,
        
        /// <remarks/>
        IHRP,
        
        /// <remarks/>
        INTC,
        
        /// <remarks/>
        INSU,
        
        /// <remarks/>
        INTE,
        
        /// <remarks/>
        LICF,
        
        /// <remarks/>
        LOAN,
        
        /// <remarks/>
        LOAR,
        
        /// <remarks/>
        NETT,
        
        /// <remarks/>
        PAYR,
        
        /// <remarks/>
        PENS,
        
        /// <remarks/>
        REFU,
        
        /// <remarks/>
        RENT,
        
        /// <remarks/>
        ROYA,
        
        /// <remarks/>
        SCVE,
        
        /// <remarks/>
        SECU,
        
        /// <remarks/>
        SSBE,
        
        /// <remarks/>
        SUBS,
        
        /// <remarks/>
        TAXS,
        
        /// <remarks/>
        VATX,
        
        /// <remarks/>
        COMT,
        
        /// <remarks/>
        DBTC,
        
        /// <remarks/>
        SUPP,
        
        /// <remarks/>
        HEDG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PaymentIdentification {
        
        private string instrIdField;
        
        private string endToEndIdField;
        
        private string pmtRmtIdField;
        
        /// <remarks/>
        public string InstrId {
            get {
                return this.instrIdField;
            }
            set {
                this.instrIdField = value;
            }
        }
        
        /// <remarks/>
        public string EndToEndId {
            get {
                return this.endToEndIdField;
            }
            set {
                this.endToEndIdField = value;
            }
        }
        
        /// <remarks/>
        public string PmtRmtId {
            get {
                return this.pmtRmtIdField;
            }
            set {
                this.pmtRmtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class GenericPaymentTransaction2 {
        
        private PaymentIdentification pmtIdField;
        
        private PurposeChoice purpField;
        
        private AmountType1Choice amtField;
        
        private PartyIdentification1 cdtrField;
        
        private string cdtrCtryOfResField;
        
        private BICIdentification1 fnlAgtField;
        
        private ChargeBearer1Code chrgBrField;
        
        private AccountIdentification2 cdtrAcctField;
        
        private string xchgCtrctRefField;
        
        private RemittanceInformation3Choice rmtInfField;
        
        /// <remarks/>
        public PaymentIdentification PmtId {
            get {
                return this.pmtIdField;
            }
            set {
                this.pmtIdField = value;
            }
        }
        
        /// <remarks/>
        public PurposeChoice Purp {
            get {
                return this.purpField;
            }
            set {
                this.purpField = value;
            }
        }
        
        /// <remarks/>
        public AmountType1Choice Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public string CdtrCtryOfRes {
            get {
                return this.cdtrCtryOfResField;
            }
            set {
                this.cdtrCtryOfResField = value;
            }
        }
        
        /// <remarks/>
        public BICIdentification1 FnlAgt {
            get {
                return this.fnlAgtField;
            }
            set {
                this.fnlAgtField = value;
            }
        }
        
        /// <remarks/>
        public ChargeBearer1Code ChrgBr {
            get {
                return this.chrgBrField;
            }
            set {
                this.chrgBrField = value;
            }
        }
        
        /// <remarks/>
        public AccountIdentification2 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public string XchgCtrctRef {
            get {
                return this.xchgCtrctRefField;
            }
            set {
                this.xchgCtrctRefField = value;
            }
        }
        
        /// <remarks/>
        public RemittanceInformation3Choice RmtInf {
            get {
                return this.rmtInfField;
            }
            set {
                this.rmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class BICIdentification1 {
        
        private string bICField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum ChargeBearer1Code {
        
        /// <remarks/>
        OUR,
        
        /// <remarks/>
        BEN,
        
        /// <remarks/>
        SHA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class SimpleIdentificationInformation {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class AccountIdentification1Choice {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DmstAcct", typeof(SimpleIdentificationInformation))]
        [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UPIC", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        BBAN,
        
        /// <remarks/>
        DmstAcct,
        
        /// <remarks/>
        IBAN,
        
        /// <remarks/>
        UPIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class CashAccount3 {
        
        private AccountIdentification1Choice idField;
        
        private CashAccountType3Code tpField;
        
        private bool tpFieldSpecified;
        
        private string ccyField;
        
        private string nmField;
        
        /// <remarks/>
        public AccountIdentification1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountType3Code Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TpSpecified {
            get {
                return this.tpFieldSpecified;
            }
            set {
                this.tpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum CashAccountType3Code {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        SACC,
        
        /// <remarks/>
        CACC,
        
        /// <remarks/>
        SVGS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PaymentSchemeChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CashClearingSystem2Code))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryInf", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum CashClearingSystem2Code {
        
        /// <remarks/>
        RTG,
        
        /// <remarks/>
        ACH,
        
        /// <remarks/>
        CHI,
        
        /// <remarks/>
        FDN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class SettlementPriorityChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtSchme", typeof(PaymentSchemeChoice))]
        [System.Xml.Serialization.XmlElementAttribute("Prty", typeof(Priority2Code))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum Priority2Code {
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NORM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class CreditTransferTypeIdentification {
        
        private object itemField;
        
        private Priority2Code instrPrtyField;
        
        private bool instrPrtyFieldSpecified;
        
        private SettlementPriorityChoice sttlmPrtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CreditTransferType2Code))]
        [System.Xml.Serialization.XmlElementAttribute("LclInstrm", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public Priority2Code InstrPrty {
            get {
                return this.instrPrtyField;
            }
            set {
                this.instrPrtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrPrtySpecified {
            get {
                return this.instrPrtyFieldSpecified;
            }
            set {
                this.instrPrtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SettlementPriorityChoice SttlmPrty {
            get {
                return this.sttlmPrtyField;
            }
            set {
                this.sttlmPrtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public enum CreditTransferType2Code {
        
        /// <remarks/>
        CORT,
        
        /// <remarks/>
        SALA,
        
        /// <remarks/>
        TREA,
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        DIVI,
        
        /// <remarks/>
        GOVT,
        
        /// <remarks/>
        INTE,
        
        /// <remarks/>
        LOAN,
        
        /// <remarks/>
        PENS,
        
        /// <remarks/>
        SECU,
        
        /// <remarks/>
        SSBE,
        
        /// <remarks/>
        SUPP,
        
        /// <remarks/>
        TAXS,
        
        /// <remarks/>
        TRAD,
        
        /// <remarks/>
        VATX,
        
        /// <remarks/>
        HEDG,
        
        /// <remarks/>
        INTC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PaymentInformation7 {
        
        private System.DateTime reqdExctnDtField;
        
        private CreditTransferTypeIdentification cdtTrfTpIdField;
        
        private PartyIdentification1 dbtrField;
        
        private string dbtrCtryOfResField;
        
        private CashAccount3 dbtrAcctField;
        
        private BICIdentification1 frstAgtField;
        
        private CashAccount3 chrgsAcctField;
        
        private BICIdentification1 chrgsAcctAgtField;
        
        private GenericPaymentTransaction2[] pmtTxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReqdExctnDt {
            get {
                return this.reqdExctnDtField;
            }
            set {
                this.reqdExctnDtField = value;
            }
        }
        
        /// <remarks/>
        public CreditTransferTypeIdentification CdtTrfTpId {
            get {
                return this.cdtTrfTpIdField;
            }
            set {
                this.cdtTrfTpIdField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public string DbtrCtryOfRes {
            get {
                return this.dbtrCtryOfResField;
            }
            set {
                this.dbtrCtryOfResField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount3 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BICIdentification1 FrstAgt {
            get {
                return this.frstAgtField;
            }
            set {
                this.frstAgtField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount3 ChrgsAcct {
            get {
                return this.chrgsAcctField;
            }
            set {
                this.chrgsAcctField = value;
            }
        }
        
        /// <remarks/>
        public BICIdentification1 ChrgsAcctAgt {
            get {
                return this.chrgsAcctAgtField;
            }
            set {
                this.chrgsAcctAgtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtTx")]
        public GenericPaymentTransaction2[] PmtTx {
            get {
                return this.pmtTxField;
            }
            set {
                this.pmtTxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class GenericIdentification4 {
        
        private string idField;
        
        private string idTpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IdTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class PersonIdentification2 {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string issrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlnRegnNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DrvrsLicNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("IdntyCardNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MplyrIdNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("OthrId", typeof(GenericIdentification4))]
        [System.Xml.Serialization.XmlElementAttribute("PsptNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("SclSctyNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TaxIdNb", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AlnRegnNb,
        
        /// <remarks/>
        DrvrsLicNb,
        
        /// <remarks/>
        IdntyCardNb,
        
        /// <remarks/>
        MplyrIdNb,
        
        /// <remarks/>
        OthrId,
        
        /// <remarks/>
        PsptNb,
        
        /// <remarks/>
        SclSctyNb,
        
        /// <remarks/>
        TaxIdNb,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class GenericIdentification3 {
        
        private string idField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class NonFinancialInstitutionIdentification1 {
        
        private string bEIField;
        
        private string eANGLNField;
        
        private string uSCHUField;
        
        private string dUNSField;
        
        private string bkPtyIdField;
        
        private string taxIdNbField;
        
        private GenericIdentification3 prtryIdField;
        
        /// <remarks/>
        public string BEI {
            get {
                return this.bEIField;
            }
            set {
                this.bEIField = value;
            }
        }
        
        /// <remarks/>
        public string EANGLN {
            get {
                return this.eANGLNField;
            }
            set {
                this.eANGLNField = value;
            }
        }
        
        /// <remarks/>
        public string USCHU {
            get {
                return this.uSCHUField;
            }
            set {
                this.uSCHUField = value;
            }
        }
        
        /// <remarks/>
        public string DUNS {
            get {
                return this.dUNSField;
            }
            set {
                this.dUNSField = value;
            }
        }
        
        /// <remarks/>
        public string BkPtyId {
            get {
                return this.bkPtyIdField;
            }
            set {
                this.bkPtyIdField = value;
            }
        }
        
        /// <remarks/>
        public string TaxIdNb {
            get {
                return this.taxIdNbField;
            }
            set {
                this.taxIdNbField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification3 PrtryId {
            get {
                return this.prtryIdField;
            }
            set {
                this.prtryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.001.003.01")]
    public partial class Party1Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(NonFinancialInstitutionIdentification1))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification2))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
