//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.PainM011V00102 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IsNullable=false)]
    public partial class Document {
        
        private MandateCancellationRequestV02 mndtCxlReqField;
        
        /// <remarks/>
        public MandateCancellationRequestV02 MndtCxlReq {
            get {
                return this.mndtCxlReqField;
            }
            set {
                this.mndtCxlReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class MandateCancellationRequestV02 {
        
        private GroupHeader47 grpHdrField;
        
        private MandateCancellation2 undrlygCxlDtlsField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public GroupHeader47 GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        public MandateCancellation2 UndrlygCxlDtls {
            get {
                return this.undrlygCxlDtlsField;
            }
            set {
                this.undrlygCxlDtlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class GroupHeader47 {
        
        private string msgIdField;
        
        private System.DateTime creDtTmField;
        
        private Authorisation1Choice[] authstnField;
        
        private PartyIdentification43 initgPtyField;
        
        private BranchAndFinancialInstitutionIdentification5 instgAgtField;
        
        private BranchAndFinancialInstitutionIdentification5 instdAgtField;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Authstn")]
        public Authorisation1Choice[] Authstn {
            get {
                return this.authstnField;
            }
            set {
                this.authstnField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 InitgPty {
            get {
                return this.initgPtyField;
            }
            set {
                this.initgPtyField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification5 InstgAgt {
            get {
                return this.instgAgtField;
            }
            set {
                this.instgAgtField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification5 InstdAgt {
            get {
                return this.instdAgtField;
            }
            set {
                this.instdAgtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class Authorisation1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(Authorisation1Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum Authorisation1Code {
        
        /// <remarks/>
        AUTH,
        
        /// <remarks/>
        FDET,
        
        /// <remarks/>
        FSUM,
        
        /// <remarks/>
        ILEV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ReferredDocumentType1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DocumentType5Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum DocumentType5Code {
        
        /// <remarks/>
        MSIN,
        
        /// <remarks/>
        CNFA,
        
        /// <remarks/>
        DNFA,
        
        /// <remarks/>
        CINV,
        
        /// <remarks/>
        CREN,
        
        /// <remarks/>
        DEBN,
        
        /// <remarks/>
        HIRI,
        
        /// <remarks/>
        SBIN,
        
        /// <remarks/>
        CMCN,
        
        /// <remarks/>
        SOAC,
        
        /// <remarks/>
        DISP,
        
        /// <remarks/>
        BOLD,
        
        /// <remarks/>
        VCHR,
        
        /// <remarks/>
        AROI,
        
        /// <remarks/>
        TSUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ReferredDocumentType2 {
        
        private ReferredDocumentType1Choice cdOrPrtryField;
        
        private string issrField;
        
        /// <remarks/>
        public ReferredDocumentType1Choice CdOrPrtry {
            get {
                return this.cdOrPrtryField;
            }
            set {
                this.cdOrPrtryField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ReferredDocumentInformation3 {
        
        private ReferredDocumentType2 tpField;
        
        private string nbField;
        
        private System.DateTime rltdDtField;
        
        private bool rltdDtFieldSpecified;
        
        /// <remarks/>
        public ReferredDocumentType2 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RltdDt {
            get {
                return this.rltdDtField;
            }
            set {
                this.rltdDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RltdDtSpecified {
            get {
                return this.rltdDtFieldSpecified;
            }
            set {
                this.rltdDtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class CashAccountType2Choice {
        
        private string itemField;
        
        private ItemChoiceType8 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType8 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType8 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class AccountSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType7 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType7 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType7 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class GenericAccountIdentification1 {
        
        private string idField;
        
        private AccountSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public AccountSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class AccountIdentification4Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class CashAccount24 {
        
        private AccountIdentification4Choice idField;
        
        private CashAccountType2Choice tpField;
        
        private string ccyField;
        
        private string nmField;
        
        /// <remarks/>
        public AccountIdentification4Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountType2Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ActiveOrHistoricCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class DatePeriodDetails1 {
        
        private System.DateTime frDtField;
        
        private System.DateTime toDtField;
        
        private bool toDtFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FrDt {
            get {
                return this.frDtField;
            }
            set {
                this.frDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ToDt {
            get {
                return this.toDtField;
            }
            set {
                this.toDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToDtSpecified {
            get {
                return this.toDtFieldSpecified;
            }
            set {
                this.toDtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class MandateOccurrences2 {
        
        private SequenceType2Code seqTpField;
        
        private Frequency6Code frqcyField;
        
        private bool frqcyFieldSpecified;
        
        private DatePeriodDetails1 drtnField;
        
        private System.DateTime frstColltnDtField;
        
        private bool frstColltnDtFieldSpecified;
        
        private System.DateTime fnlColltnDtField;
        
        private bool fnlColltnDtFieldSpecified;
        
        /// <remarks/>
        public SequenceType2Code SeqTp {
            get {
                return this.seqTpField;
            }
            set {
                this.seqTpField = value;
            }
        }
        
        /// <remarks/>
        public Frequency6Code Frqcy {
            get {
                return this.frqcyField;
            }
            set {
                this.frqcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrqcySpecified {
            get {
                return this.frqcyFieldSpecified;
            }
            set {
                this.frqcyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DatePeriodDetails1 Drtn {
            get {
                return this.drtnField;
            }
            set {
                this.drtnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FrstColltnDt {
            get {
                return this.frstColltnDtField;
            }
            set {
                this.frstColltnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrstColltnDtSpecified {
            get {
                return this.frstColltnDtFieldSpecified;
            }
            set {
                this.frstColltnDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FnlColltnDt {
            get {
                return this.fnlColltnDtField;
            }
            set {
                this.fnlColltnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FnlColltnDtSpecified {
            get {
                return this.fnlColltnDtFieldSpecified;
            }
            set {
                this.fnlColltnDtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum SequenceType2Code {
        
        /// <remarks/>
        RCUR,
        
        /// <remarks/>
        OOFF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum Frequency6Code {
        
        /// <remarks/>
        YEAR,
        
        /// <remarks/>
        MNTH,
        
        /// <remarks/>
        QURT,
        
        /// <remarks/>
        MIAN,
        
        /// <remarks/>
        WEEK,
        
        /// <remarks/>
        DAIL,
        
        /// <remarks/>
        ADHO,
        
        /// <remarks/>
        INDA,
        
        /// <remarks/>
        FRTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class LocalInstrument2Choice {
        
        private string itemField;
        
        private ItemChoiceType6 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType6 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType6 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ServiceLevel8Choice {
        
        private string itemField;
        
        private ItemChoiceType5 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType5 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType5 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class MandateTypeInformation1 {
        
        private ServiceLevel8Choice svcLvlField;
        
        private LocalInstrument2Choice lclInstrmField;
        
        /// <remarks/>
        public ServiceLevel8Choice SvcLvl {
            get {
                return this.svcLvlField;
            }
            set {
                this.svcLvlField = value;
            }
        }
        
        /// <remarks/>
        public LocalInstrument2Choice LclInstrm {
            get {
                return this.lclInstrmField;
            }
            set {
                this.lclInstrmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class Mandate1 {
        
        private string mndtIdField;
        
        private string mndtReqIdField;
        
        private MandateTypeInformation1 tpField;
        
        private MandateOccurrences2 ocrncsField;
        
        private ActiveOrHistoricCurrencyAndAmount colltnAmtField;
        
        private ActiveOrHistoricCurrencyAndAmount maxAmtField;
        
        private PartyIdentification43 cdtrSchmeIdField;
        
        private PartyIdentification43 cdtrField;
        
        private CashAccount24 cdtrAcctField;
        
        private BranchAndFinancialInstitutionIdentification5 cdtrAgtField;
        
        private PartyIdentification43 ultmtCdtrField;
        
        private PartyIdentification43 dbtrField;
        
        private CashAccount24 dbtrAcctField;
        
        private BranchAndFinancialInstitutionIdentification5 dbtrAgtField;
        
        private PartyIdentification43 ultmtDbtrField;
        
        private ReferredDocumentInformation3 rfrdDocField;
        
        /// <remarks/>
        public string MndtId {
            get {
                return this.mndtIdField;
            }
            set {
                this.mndtIdField = value;
            }
        }
        
        /// <remarks/>
        public string MndtReqId {
            get {
                return this.mndtReqIdField;
            }
            set {
                this.mndtReqIdField = value;
            }
        }
        
        /// <remarks/>
        public MandateTypeInformation1 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public MandateOccurrences2 Ocrncs {
            get {
                return this.ocrncsField;
            }
            set {
                this.ocrncsField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount ColltnAmt {
            get {
                return this.colltnAmtField;
            }
            set {
                this.colltnAmtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount MaxAmt {
            get {
                return this.maxAmtField;
            }
            set {
                this.maxAmtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 CdtrSchmeId {
            get {
                return this.cdtrSchmeIdField;
            }
            set {
                this.cdtrSchmeIdField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount24 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification5 CdtrAgt {
            get {
                return this.cdtrAgtField;
            }
            set {
                this.cdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 UltmtCdtr {
            get {
                return this.ultmtCdtrField;
            }
            set {
                this.ultmtCdtrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount24 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification5 DbtrAgt {
            get {
                return this.dbtrAgtField;
            }
            set {
                this.dbtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification43 UltmtDbtr {
            get {
                return this.ultmtDbtrField;
            }
            set {
                this.ultmtDbtrField = value;
            }
        }
        
        /// <remarks/>
        public ReferredDocumentInformation3 RfrdDoc {
            get {
                return this.rfrdDocField;
            }
            set {
                this.rfrdDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class PartyIdentification43 {
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        private Party11Choice idField;
        
        private string ctryOfResField;
        
        private ContactDetails2 ctctDtlsField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public Party11Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
        
        /// <remarks/>
        public ContactDetails2 CtctDtls {
            get {
                return this.ctctDtlsField;
            }
            set {
                this.ctctDtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class PostalAddress6 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string deptField;
        
        private string subDeptField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        private string[] adrLineField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
        
        /// <remarks/>
        public string SubDept {
            get {
                return this.subDeptField;
            }
            set {
                this.subDeptField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class Party11Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification8))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification5))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class OrganisationIdentification8 {
        
        private string anyBICField;
        
        private GenericOrganisationIdentification1[] othrField;
        
        /// <remarks/>
        public string AnyBIC {
            get {
                return this.anyBICField;
            }
            set {
                this.anyBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericOrganisationIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class GenericOrganisationIdentification1 {
        
        private string idField;
        
        private OrganisationIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public OrganisationIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class OrganisationIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class PersonIdentification5 {
        
        private DateAndPlaceOfBirth dtAndPlcOfBirthField;
        
        private GenericPersonIdentification1[] othrField;
        
        /// <remarks/>
        public DateAndPlaceOfBirth DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericPersonIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class DateAndPlaceOfBirth {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class GenericPersonIdentification1 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class PersonIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ContactDetails2 {
        
        private NamePrefix1Code nmPrfxField;
        
        private bool nmPrfxFieldSpecified;
        
        private string nmField;
        
        private string phneNbField;
        
        private string mobNbField;
        
        private string faxNbField;
        
        private string emailAdrField;
        
        private string othrField;
        
        /// <remarks/>
        public NamePrefix1Code NmPrfx {
            get {
                return this.nmPrfxField;
            }
            set {
                this.nmPrfxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NmPrfxSpecified {
            get {
                return this.nmPrfxFieldSpecified;
            }
            set {
                this.nmPrfxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public string PhneNb {
            get {
                return this.phneNbField;
            }
            set {
                this.phneNbField = value;
            }
        }
        
        /// <remarks/>
        public string MobNb {
            get {
                return this.mobNbField;
            }
            set {
                this.mobNbField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNb {
            get {
                return this.faxNbField;
            }
            set {
                this.faxNbField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public string Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public enum NamePrefix1Code {
        
        /// <remarks/>
        DOCT,
        
        /// <remarks/>
        MIST,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MADM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class BranchAndFinancialInstitutionIdentification5 {
        
        private FinancialInstitutionIdentification8 finInstnIdField;
        
        private BranchData2 brnchIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentification8 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
        
        /// <remarks/>
        public BranchData2 BrnchId {
            get {
                return this.brnchIdField;
            }
            set {
                this.brnchIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class FinancialInstitutionIdentification8 {
        
        private string bICFIField;
        
        private ClearingSystemMemberIdentification2 clrSysMmbIdField;
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        private GenericFinancialIdentification1 othrField;
        
        /// <remarks/>
        public string BICFI {
            get {
                return this.bICFIField;
            }
            set {
                this.bICFIField = value;
            }
        }
        
        /// <remarks/>
        public ClearingSystemMemberIdentification2 ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public GenericFinancialIdentification1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ClearingSystemMemberIdentification2 {
        
        private ClearingSystemIdentification2Choice clrSysIdField;
        
        private string mmbIdField;
        
        /// <remarks/>
        public ClearingSystemIdentification2Choice ClrSysId {
            get {
                return this.clrSysIdField;
            }
            set {
                this.clrSysIdField = value;
            }
        }
        
        /// <remarks/>
        public string MmbId {
            get {
                return this.mmbIdField;
            }
            set {
                this.mmbIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class ClearingSystemIdentification2Choice {
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class GenericFinancialIdentification1 {
        
        private string idField;
        
        private FinancialIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public FinancialIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class FinancialIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class BranchData2 {
        
        private string idField;
        
        private string nmField;
        
        private PostalAddress6 pstlAdrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class OriginalMandate2Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgnlMndt", typeof(Mandate1))]
        [System.Xml.Serialization.XmlElementAttribute("OrgnlMndtId", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class MandateReason1Choice {
        
        private string itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class PaymentCancellationReason1 {
        
        private PartyIdentification43 orgtrField;
        
        private MandateReason1Choice rsnField;
        
        private string[] addtlInfField;
        
        /// <remarks/>
        public PartyIdentification43 Orgtr {
            get {
                return this.orgtrField;
            }
            set {
                this.orgtrField = value;
            }
        }
        
        /// <remarks/>
        public MandateReason1Choice Rsn {
            get {
                return this.rsnField;
            }
            set {
                this.rsnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
        public string[] AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class OriginalMessageInformation1 {
        
        private string msgIdField;
        
        private string msgNmIdField;
        
        private System.DateTime creDtTmField;
        
        private bool creDtTmFieldSpecified;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public string MsgNmId {
            get {
                return this.msgNmIdField;
            }
            set {
                this.msgNmIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreDtTmSpecified {
            get {
                return this.creDtTmFieldSpecified;
            }
            set {
                this.creDtTmFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.011.001.02")]
    public partial class MandateCancellation2 {
        
        private OriginalMessageInformation1 orgnlMsgInfField;
        
        private PaymentCancellationReason1 cxlRsnField;
        
        private OriginalMandate2Choice orgnlMndtField;
        
        /// <remarks/>
        public OriginalMessageInformation1 OrgnlMsgInf {
            get {
                return this.orgnlMsgInfField;
            }
            set {
                this.orgnlMsgInfField = value;
            }
        }
        
        /// <remarks/>
        public PaymentCancellationReason1 CxlRsn {
            get {
                return this.cxlRsnField;
            }
            set {
                this.cxlRsnField = value;
            }
        }
        
        /// <remarks/>
        public OriginalMandate2Choice OrgnlMndt {
            get {
                return this.orgnlMndtField;
            }
            set {
                this.orgnlMndtField = value;
            }
        }
    }
}
