//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Iso20022.Contracts.PainM002V00101 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01", IsNullable=false)]
    public partial class Document {
        
        private pain00200101 pain00200101Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pain.002.001.01")]
        public pain00200101 pain00200101 {
            get {
                return this.pain00200101Field;
            }
            set {
                this.pain00200101Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="pain.002.001.01", Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class pain00200101 {
        
        private GeneralInformation1 gnlInfField;
        
        private OriginalGroupReferenceInformation1 orgnlGrpRefInfAndStsField;
        
        private PaymentInformation9[] orgnlPmtInfField;
        
        /// <remarks/>
        public GeneralInformation1 GnlInf {
            get {
                return this.gnlInfField;
            }
            set {
                this.gnlInfField = value;
            }
        }
        
        /// <remarks/>
        public OriginalGroupReferenceInformation1 OrgnlGrpRefInfAndSts {
            get {
                return this.orgnlGrpRefInfAndStsField;
            }
            set {
                this.orgnlGrpRefInfAndStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgnlPmtInf")]
        public PaymentInformation9[] OrgnlPmtInf {
            get {
                return this.orgnlPmtInfField;
            }
            set {
                this.orgnlPmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class GeneralInformation1 {
        
        private string pmtInitnStsIdField;
        
        private System.DateTime creDtTmField;
        
        private BranchAndFinancialInstitutionIdentification fwdgAgtField;
        
        private PartyIdentification1 initgPtyField;
        
        private BranchAndFinancialInstitutionIdentification frstAgtField;
        
        /// <remarks/>
        public string PmtInitnStsId {
            get {
                return this.pmtInitnStsIdField;
            }
            set {
                this.pmtInitnStsIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification FwdgAgt {
            get {
                return this.fwdgAgtField;
            }
            set {
                this.fwdgAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 InitgPty {
            get {
                return this.initgPtyField;
            }
            set {
                this.initgPtyField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification FrstAgt {
            get {
                return this.frstAgtField;
            }
            set {
                this.frstAgtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class BranchAndFinancialInstitutionIdentification {
        
        private FinancialInstitutionIdentification1 finInstnIdField;
        
        private BranchData brnchIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentification1 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
        
        /// <remarks/>
        public BranchData BrnchId {
            get {
                return this.brnchIdField;
            }
            set {
                this.brnchIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class FinancialInstitutionIdentification1 {
        
        private string bICField;
        
        private ClearingSystemMemberIdentificationChoice clrSysMmbIdField;
        
        private string nmField;
        
        private PostalAddress1 pstlAdrField;
        
        private GenericIdentification3 prtryIdField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public ClearingSystemMemberIdentificationChoice ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification3 PrtryId {
            get {
                return this.prtryIdField;
            }
            set {
                this.prtryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class ClearingSystemMemberIdentificationChoice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATBLZ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("AUBSBs", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("AUBSBx", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CACPA", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CHBC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CHSIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DEBLZ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ESNCC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("GBSC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("HKNCC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("IENSC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ITNCC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NZNCC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PTNCC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("RUCB", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("USCH", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("USCHU", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("USFW", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ZANCC", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        ATBLZ,
        
        /// <remarks/>
        AUBSBs,
        
        /// <remarks/>
        AUBSBx,
        
        /// <remarks/>
        CACPA,
        
        /// <remarks/>
        CHBC,
        
        /// <remarks/>
        CHSIC,
        
        /// <remarks/>
        DEBLZ,
        
        /// <remarks/>
        ESNCC,
        
        /// <remarks/>
        GBSC,
        
        /// <remarks/>
        HKNCC,
        
        /// <remarks/>
        IENSC,
        
        /// <remarks/>
        ITNCC,
        
        /// <remarks/>
        NZNCC,
        
        /// <remarks/>
        PTNCC,
        
        /// <remarks/>
        RUCB,
        
        /// <remarks/>
        USCH,
        
        /// <remarks/>
        USCHU,
        
        /// <remarks/>
        USFW,
        
        /// <remarks/>
        ZANCC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class EquivalentAmount {
        
        private CurrencyAndAmount amtField;
        
        private string ccyOfTrfField;
        
        /// <remarks/>
        public CurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public string CcyOfTrf {
            get {
                return this.ccyOfTrfField;
            }
            set {
                this.ccyOfTrfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class CurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class AmountType1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EqvtAmt", typeof(EquivalentAmount))]
        [System.Xml.Serialization.XmlElementAttribute("InstdAmt", typeof(CurrencyAndAmount))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class OriginalTransactionInformation1 {
        
        private AmountType1Choice amtField;
        
        private PartyIdentification1 cdtrField;
        
        private CashAccount3 cdtrAcctField;
        
        private BranchAndFinancialInstitutionIdentification fnlAgtField;
        
        /// <remarks/>
        public AmountType1Choice Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount3 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification FnlAgt {
            get {
                return this.fnlAgtField;
            }
            set {
                this.fnlAgtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PartyIdentification1 {
        
        private string nmField;
        
        private PostalAddress1 pstlAdrField;
        
        private Party1Choice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public Party1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PostalAddress1 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class Party1Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(NonFinancialInstitutionIdentification1))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification2))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class NonFinancialInstitutionIdentification1 {
        
        private string bEIField;
        
        private string eANGLNField;
        
        private string uSCHUField;
        
        private string dUNSField;
        
        private string bkPtyIdField;
        
        private string taxIdNbField;
        
        private GenericIdentification3 prtryIdField;
        
        /// <remarks/>
        public string BEI {
            get {
                return this.bEIField;
            }
            set {
                this.bEIField = value;
            }
        }
        
        /// <remarks/>
        public string EANGLN {
            get {
                return this.eANGLNField;
            }
            set {
                this.eANGLNField = value;
            }
        }
        
        /// <remarks/>
        public string USCHU {
            get {
                return this.uSCHUField;
            }
            set {
                this.uSCHUField = value;
            }
        }
        
        /// <remarks/>
        public string DUNS {
            get {
                return this.dUNSField;
            }
            set {
                this.dUNSField = value;
            }
        }
        
        /// <remarks/>
        public string BkPtyId {
            get {
                return this.bkPtyIdField;
            }
            set {
                this.bkPtyIdField = value;
            }
        }
        
        /// <remarks/>
        public string TaxIdNb {
            get {
                return this.taxIdNbField;
            }
            set {
                this.taxIdNbField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification3 PrtryId {
            get {
                return this.prtryIdField;
            }
            set {
                this.prtryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class GenericIdentification3 {
        
        private string idField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PersonIdentification2 {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string issrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlnRegnNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DrvrsLicNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("IdntyCardNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MplyrIdNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("OthrId", typeof(GenericIdentification4))]
        [System.Xml.Serialization.XmlElementAttribute("PsptNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("SclSctyNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TaxIdNb", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class GenericIdentification4 {
        
        private string idField;
        
        private string idTpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IdTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        AlnRegnNb,
        
        /// <remarks/>
        DrvrsLicNb,
        
        /// <remarks/>
        IdntyCardNb,
        
        /// <remarks/>
        MplyrIdNb,
        
        /// <remarks/>
        OthrId,
        
        /// <remarks/>
        PsptNb,
        
        /// <remarks/>
        SclSctyNb,
        
        /// <remarks/>
        TaxIdNb,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class CashAccount3 {
        
        private AccountIdentification1Choice idField;
        
        private CashAccountType3Code tpField;
        
        private bool tpFieldSpecified;
        
        private string ccyField;
        
        private string nmField;
        
        /// <remarks/>
        public AccountIdentification1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountType3Code Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TpSpecified {
            get {
                return this.tpFieldSpecified;
            }
            set {
                this.tpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class AccountIdentification1Choice {
        
        private object itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DmstAcct", typeof(SimpleIdentificationInformation))]
        [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UPIC", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class SimpleIdentificationInformation {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        BBAN,
        
        /// <remarks/>
        DmstAcct,
        
        /// <remarks/>
        IBAN,
        
        /// <remarks/>
        UPIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum CashAccountType3Code {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        SACC,
        
        /// <remarks/>
        CACC,
        
        /// <remarks/>
        SVGS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PaymentIdentification {
        
        private string instrIdField;
        
        private string endToEndIdField;
        
        private string pmtRmtIdField;
        
        /// <remarks/>
        public string InstrId {
            get {
                return this.instrIdField;
            }
            set {
                this.instrIdField = value;
            }
        }
        
        /// <remarks/>
        public string EndToEndId {
            get {
                return this.endToEndIdField;
            }
            set {
                this.endToEndIdField = value;
            }
        }
        
        /// <remarks/>
        public string PmtRmtId {
            get {
                return this.pmtRmtIdField;
            }
            set {
                this.pmtRmtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PaymentReference1 {
        
        private PaymentIdentification pmtIdField;
        
        private PaymentTransactionStatusCode txStsField;
        
        private bool txStsFieldSpecified;
        
        private PaymentReject1Code stsRsnField;
        
        private bool stsRsnFieldSpecified;
        
        private string addtlInfField;
        
        private OriginalTransactionInformation1 orgnlTxInfField;
        
        /// <remarks/>
        public PaymentIdentification PmtId {
            get {
                return this.pmtIdField;
            }
            set {
                this.pmtIdField = value;
            }
        }
        
        /// <remarks/>
        public PaymentTransactionStatusCode TxSts {
            get {
                return this.txStsField;
            }
            set {
                this.txStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxStsSpecified {
            get {
                return this.txStsFieldSpecified;
            }
            set {
                this.txStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PaymentReject1Code StsRsn {
            get {
                return this.stsRsnField;
            }
            set {
                this.stsRsnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StsRsnSpecified {
            get {
                return this.stsRsnFieldSpecified;
            }
            set {
                this.stsRsnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
        
        /// <remarks/>
        public OriginalTransactionInformation1 OrgnlTxInf {
            get {
                return this.orgnlTxInfField;
            }
            set {
                this.orgnlTxInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum PaymentTransactionStatusCode {
        
        /// <remarks/>
        ACTC,
        
        /// <remarks/>
        RJCT,
        
        /// <remarks/>
        PDNG,
        
        /// <remarks/>
        ACCP,
        
        /// <remarks/>
        ACSP,
        
        /// <remarks/>
        ACSC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum PaymentReject1Code {
        
        /// <remarks/>
        AC01,
        
        /// <remarks/>
        AC02,
        
        /// <remarks/>
        AC03,
        
        /// <remarks/>
        AC04,
        
        /// <remarks/>
        AC05,
        
        /// <remarks/>
        AC06,
        
        /// <remarks/>
        AM01,
        
        /// <remarks/>
        AM02,
        
        /// <remarks/>
        AM03,
        
        /// <remarks/>
        AM04,
        
        /// <remarks/>
        AM05,
        
        /// <remarks/>
        AM06,
        
        /// <remarks/>
        AM07,
        
        /// <remarks/>
        AM08,
        
        /// <remarks/>
        BE01,
        
        /// <remarks/>
        BE02,
        
        /// <remarks/>
        BE03,
        
        /// <remarks/>
        BE04,
        
        /// <remarks/>
        BE05,
        
        /// <remarks/>
        AG01,
        
        /// <remarks/>
        AG02,
        
        /// <remarks/>
        DT01,
        
        /// <remarks/>
        MS01,
        
        /// <remarks/>
        PY01,
        
        /// <remarks/>
        RF01,
        
        /// <remarks/>
        RC01,
        
        /// <remarks/>
        RC02,
        
        /// <remarks/>
        RC03,
        
        /// <remarks/>
        RC04,
        
        /// <remarks/>
        TM01,
        
        /// <remarks/>
        ED01,
        
        /// <remarks/>
        ED02,
        
        /// <remarks/>
        ED03,
        
        /// <remarks/>
        ED04,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PaymentSchemeChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CashClearingSystem2Code))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryInf", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum CashClearingSystem2Code {
        
        /// <remarks/>
        RTG,
        
        /// <remarks/>
        ACH,
        
        /// <remarks/>
        CHI,
        
        /// <remarks/>
        FDN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class SettlementPriorityChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtSchme", typeof(PaymentSchemeChoice))]
        [System.Xml.Serialization.XmlElementAttribute("Prty", typeof(Priority2Code))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum Priority2Code {
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NORM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class CreditTransferTypeIdentification {
        
        private object itemField;
        
        private Priority2Code instrPrtyField;
        
        private bool instrPrtyFieldSpecified;
        
        private SettlementPriorityChoice sttlmPrtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CreditTransferType2Code))]
        [System.Xml.Serialization.XmlElementAttribute("LclInstrm", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public Priority2Code InstrPrty {
            get {
                return this.instrPrtyField;
            }
            set {
                this.instrPrtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrPrtySpecified {
            get {
                return this.instrPrtyFieldSpecified;
            }
            set {
                this.instrPrtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SettlementPriorityChoice SttlmPrty {
            get {
                return this.sttlmPrtyField;
            }
            set {
                this.sttlmPrtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum CreditTransferType2Code {
        
        /// <remarks/>
        CORT,
        
        /// <remarks/>
        SALA,
        
        /// <remarks/>
        TREA,
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        DIVI,
        
        /// <remarks/>
        GOVT,
        
        /// <remarks/>
        INTE,
        
        /// <remarks/>
        LOAN,
        
        /// <remarks/>
        PENS,
        
        /// <remarks/>
        SECU,
        
        /// <remarks/>
        SSBE,
        
        /// <remarks/>
        SUPP,
        
        /// <remarks/>
        TAXS,
        
        /// <remarks/>
        TRAD,
        
        /// <remarks/>
        VATX,
        
        /// <remarks/>
        HEDG,
        
        /// <remarks/>
        INTC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class PaymentInformation9 {
        
        private System.DateTime reqdExctnDtField;
        
        private bool reqdExctnDtFieldSpecified;
        
        private PaymentMethod1Code pmtMtdByFrstAgtField;
        
        private bool pmtMtdByFrstAgtFieldSpecified;
        
        private CreditTransferTypeIdentification cdtTrfTpIdField;
        
        private PartyIdentification1 dbtrField;
        
        private CashAccount3 dbtrAcctField;
        
        private PaymentReference1[] orgnlTxRefInfAndStsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReqdExctnDt {
            get {
                return this.reqdExctnDtField;
            }
            set {
                this.reqdExctnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReqdExctnDtSpecified {
            get {
                return this.reqdExctnDtFieldSpecified;
            }
            set {
                this.reqdExctnDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethod1Code PmtMtdByFrstAgt {
            get {
                return this.pmtMtdByFrstAgtField;
            }
            set {
                this.pmtMtdByFrstAgtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtMtdByFrstAgtSpecified {
            get {
                return this.pmtMtdByFrstAgtFieldSpecified;
            }
            set {
                this.pmtMtdByFrstAgtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CreditTransferTypeIdentification CdtTrfTpId {
            get {
                return this.cdtTrfTpIdField;
            }
            set {
                this.cdtTrfTpIdField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification1 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccount3 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgnlTxRefInfAndSts")]
        public PaymentReference1[] OrgnlTxRefInfAndSts {
            get {
                return this.orgnlTxRefInfAndStsField;
            }
            set {
                this.orgnlTxRefInfAndStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum PaymentMethod1Code {
        
        /// <remarks/>
        CHK,
        
        /// <remarks/>
        TRF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class OriginalGroupReferenceInformation1 {
        
        private string grpIdField;
        
        private string orgnlMsgTpField;
        
        private PaymentGroupStatusCode grpStsField;
        
        private bool grpStsFieldSpecified;
        
        private PaymentReject1Code stsRsnField;
        
        private bool stsRsnFieldSpecified;
        
        private string addtlInfField;
        
        /// <remarks/>
        public string GrpId {
            get {
                return this.grpIdField;
            }
            set {
                this.grpIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlMsgTp {
            get {
                return this.orgnlMsgTpField;
            }
            set {
                this.orgnlMsgTpField = value;
            }
        }
        
        /// <remarks/>
        public PaymentGroupStatusCode GrpSts {
            get {
                return this.grpStsField;
            }
            set {
                this.grpStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrpStsSpecified {
            get {
                return this.grpStsFieldSpecified;
            }
            set {
                this.grpStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PaymentReject1Code StsRsn {
            get {
                return this.stsRsnField;
            }
            set {
                this.stsRsnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StsRsnSpecified {
            get {
                return this.stsRsnFieldSpecified;
            }
            set {
                this.stsRsnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public enum PaymentGroupStatusCode {
        
        /// <remarks/>
        ACTC,
        
        /// <remarks/>
        RCVD,
        
        /// <remarks/>
        PART,
        
        /// <remarks/>
        RJCT,
        
        /// <remarks/>
        PDNG,
        
        /// <remarks/>
        ACCP,
        
        /// <remarks/>
        ACSP,
        
        /// <remarks/>
        ACSC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:xsd:pain.002.001.01")]
    public partial class BranchData {
        
        private string idField;
        
        private string nmField;
        
        private PostalAddress1 pstlAdrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
    }
}
